input:
  input_data_lake_path: "/home/fatemeh/LakeCorrectionBench/datasets/Quintet" # path to the data lake that should have errors introduced
  output_data_lake_path: "/home/fatemeh/LakeCorrectionBench/output" # path, where the results should be stored
  algorithm: "HoloClean" # algorithm to be used for error correction
  logs_dir: "/home/fatemeh/LakeCorrectionBench/logs" # path to the directory where the logs should be stored